#!/usr/bin/env python3
"""Screen all changed paths for cleanup candidates without deleting features."""
import argparse
import json
import re
from collections import Counter
from pathlib import Path
from assign_legacy_hunks import ROOT, INV, git, read_tsv, tsv, sha
from legacy_assignment_rules import path_profile

FIELDS=('child_id','status','path','source_blob','source_bytes','classification',
        'candidate','evidence','reference_evidence','disposition','implementation_tasks','verification_tasks')
# Strings/chars are tokens, so a URL or comment delimiter inside them is not erased.
TOKENS=re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|/\*.*?\*/|//[^\n]*|\w+|[^\s]',re.S)
def tokens(s):return [m.group() for m in TOKENS.finditer(s) if not m.group().startswith(('/*','//'))]

def refs(source,name):
    proc=__import__('subprocess').run(['git','grep','-n','-F','-e',name,source,'--'],cwd=ROOT,capture_output=True)
    if proc.returncode not in (0,1):raise ValueError(proc.stderr.decode())
    return '; '.join(line.split(':',1)[1] for line in proc.stdout.decode('utf8','replace').splitlines()) or 'No literal repository reference found; dynamic/indirect use is not disproven'

def render():
    baseline=json.loads((ROOT/'migration/baseline/baseline.json').read_text());source=baseline['source']['commit']
    routes={r['path']:r for r in read_tsv(INV/'hunk-wbs.tsv')}
    rows=[]
    for f in read_tsv(INV/'changed-files.tsv'):
        p=f['path'];name=Path(p).name;r=routes[p]
        data=git('show',f['source_git_blob']) if f['source_git_blob'] else b''
        kind='functional-source-or-data';candidate='NO';ref='Assigned source/asset references retained in hunk-wbs.tsv'
        evidence='Nonempty changed content; filename alone is not removal evidence'
        action='KEEP_CONTRACT';tasks=r['implementation_tasks'];tests=r['verification_tasks']
        if not data:
            kind='empty-build-carrier';candidate='YES_AFTER_REPLACEMENT';evidence='Pinned blob is zero bytes; empty executable input can still select the C++ linker';ref=refs(source,name);action='REPLACE_BUILD_ROLE_THEN_EXCLUDE';tasks='04.008,31.018';tests='07.014,31.020'
        elif p.endswith('.bak'):
            kind='nonempty-backup-source';candidate='YES_AFTER_REFERENCE_REVIEW';evidence='Contains '+str(len(data.splitlines()))+' lines of declarations, not an empty file';ref=refs(source,name);action='COMPARE_LIVE_HEADER_THEN_EXCLUDE';tasks='08.006,31.018';tests='04.014,31.020'
        elif name=='.gitignore':
            kind='build-ignore-metadata';candidate='YES_AFTER_BUILD_REPLACEMENT';evidence='Git ignore patterns affect generated build outputs, not painting runtime';ref='Replacement build/install rules must own generated outputs';action='REPLACE_WITH_CURRENT_BUILD_RULES';tasks='04.002,31.018';tests='04.015,31.020'
        elif p=='data/mypaint-brushes/Makefile.am.skel':
            kind='executable-ruby-generator';evidence='Shebang #!/usr/bin/env ruby; generate_skel scans myb/preview pairs and writes per-directory Makefile.am';action='KEEP_GENERATOR_PURPOSE';tasks='30.017';tests='34.013,34.014'
        elif p in ('data/layer-presets/test.json','data/layer-presets/test2.json'):
            obj=json.loads(data);kind='functional-test-named-preset';evidence='JSON version='+str(obj['version'])+' contains source-layer and replacement-layer operations';action='KEEP_EDITABLE_ASSET';tasks='28.001,28.007,28.008,30.017';tests='28.013,28.015,34.014'
        elif p.startswith('app/tools/gimpimagegeneratortool.'):
            kind='executable-placeholder';candidate='YES_AFTER_DEPENDENCY_REVIEW';evidence='Actual registered tool/vfunc source; placeholder status is not evidence of absent consumers';action='PROVE_NO_PERSISTED_FEATURE_THEN_EXCLUDE';tasks='31.011,31.012';tests='31.020'
        elif p.endswith(('.c','.h','.cpp','.hpp','.pl')):
            text=data.decode('utf8','replace');head='\n'.join(text.splitlines()[:35])
            generated=re.search(r'(?i)(?:automatically generated|auto-generated|autogenerated|generated data \(by)',head)
            if generated:
                kind='generated-functional-code';candidate='YES_REGENERATE_ONLY';evidence='Source marker: '+next(l.strip() for l in head.splitlines() if re.search(r'(?i)(?:automatically generated|auto-generated|autogenerated|generated data \(by)',l));action='REGENERATE_FROM_AUTHORITATIVE_INPUT';tasks='04.013,30.013';tests='34.013'
                if p=='app/core/mypaintbrush-enum-settings.h':
                    evidence+='; named generate.py is absent in pinned tree; existing 04.013/brush-setting-generator owns recovery';tasks='04.013/brush-setting-generator'
                elif p=='app/composite/gimp-composite-generic-installer.c':
                    tasks='13.001/gegl-operation-route,31.017';tests='13.013,13.014';action='REPLACE_DISPATCH_PRESERVE_EQUATIONS'
                elif p in ('app/httpd/httpd-enums.c','app/presets/presets-enums.c'):
                    kind='generated-empty-api-carrier';evidence+='; include-only generated translation unit is not a zero-byte file'
            elif f['base_git_blob']:
                old=git('show',f['base_git_blob']).decode('utf8','replace')
                if tokens(old)==tokens(text):
                    kind='comments-or-whitespace-only-delta';candidate='YES_SOURCE_NOOP';evidence='Whole-file C-like tokens are identical after removing comments/whitespace while retaining string/char literals';action='DO_NOT_PORT_NONFUNCTIONAL_DIFF';tasks='31.018';tests='31.020'
            if p in ('app/tools/gimpmypaintbrusheditor.cpp','app/widgets/gimpmypaintbrusheditor.cpp'):
                kind='live-overlapping-editor-implementation';candidate='YES_AFTER_SHARED_REPLACEMENT';evidence='Tools and widgets editors are separate live C++ implementations, not byte-identical backup copies';action='SHARE_MODEL_KEEP_ALL_CONTROLS';tasks='24.001,24.015,24.016,31.013';tests='24.017,29.020'
        rows.append(dict(child_id=f'01.014/path-{len(rows)+1:04d}',status='DONE',path=p,source_blob=f['source_git_blob'],source_bytes=str(len(data)),classification=kind,candidate=candidate,evidence=evidence,reference_evidence=ref,disposition=action,implementation_tasks=tasks,verification_tasks=tests))
    if len(rows)!=947 or len({r['path'] for r in rows})!=947:raise ValueError('Candidate screening is incomplete')
    # Filename-counterexamples are deliberate regression checks.
    by={r['path']:r for r in rows}
    assert by['app/dummy.cpp']['classification']=='empty-build-carrier'
    assert by['app/paint/gimpmypaintcore.h.bak']['source_bytes']!='0'
    assert by['data/mypaint-brushes/Makefile.am.skel']['classification']=='executable-ruby-generator'
    assert all(by['data/layer-presets/'+p]['candidate']=='NO' for p in ('test.json','test2.json'))
    return tsv(FIELDS,rows),dict(Counter(r['classification'] for r in rows))

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--check',action='store_true');a=ap.parse_args()
    content,counts=render();p=INV/'cleanup-candidate-review.tsv'
    if a.check:
        if not p.exists() or p.read_text()!=content:raise SystemExit('Candidate review drift')
    else:p.write_text(content)
    print('947 paths screened; '+json.dumps(counts,sort_keys=True)+'; no runtime feature deletion approved')
if __name__=='__main__':main()
