#!/usr/bin/env python3
"""Relocate signed Debian autotools into an isolated legacy build prefix.

Requires the dependency directory produced by prepare-linux-build-deps.py.
No host files or application sources are changed. Generated tool copies only
relocate data paths; exact inputs and outputs are hashed in environment.json.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
import shlex


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--deps', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    deps = args.deps.resolve()
    output = args.output.resolve()
    if any(not re.fullmatch(r'[A-Za-z0-9_./+-]+', str(path)) for path in (deps, output)):
        parser.error('local build prefixes must use shell-safe paths without whitespace')
    root = deps / 'root'
    if not (deps / 'env.sh').is_file():
        parser.error('dependency env.sh is missing; prepare signed Debian dependencies first')
    inputs = {name: root / 'usr/bin' / name for name in
              ('autoconf', 'autoheader', 'autom4te', 'automake-1.17', 'aclocal-1.17',
               'libtoolize', 'intltoolize', 'gtkdocize', 'autopoint', 'm4')}
    inputs['autom4te.cfg'] = root / 'usr/share/autoconf/autom4te.cfg'
    inputs['dependency-env.sh'] = deps / 'env.sh'
    missing = [str(path) for path in inputs.values() if not path.is_file()]
    if missing:
        parser.error('missing dependency files: ' + ', '.join(missing))
    (output / 'bin').mkdir(parents=True, exist_ok=True)
    (output / 'prefix').mkdir(exist_ok=True)
    (output / 'logs').mkdir(exist_ok=True)
    files = {}
    for name in ('intltoolize', 'gtkdocize'):
        files['bin/'+name] = inputs[name].read_text().replace('prefix=/usr\n', f'prefix={root}/usr\n')
    files['bin/libtoolize'] = inputs['libtoolize'].read_text().replace(
        '"/usr/share', f'"{root}/usr/share').replace('prefix="/usr"', f'prefix="{root}/usr"')
    files['bin/automake'] = '#!/bin/sh\nexec "$GIMP_DEPS_ROOT/usr/bin/automake-1.17" "$@"\n'
    files['bin/aclocal'] = ('#!/bin/sh\nexec "$GIMP_DEPS_ROOT/usr/bin/aclocal-1.17" '
                           '--automake-acdir="$GIMP_DEPS_ROOT/usr/share/aclocal-1.17" '
                           '--system-acdir="$GIMP_DEPS_ROOT/usr/share/aclocal" "$@"\n')
    files['autom4te.cfg'] = inputs['autom4te.cfg'].read_text().replace(
        '/usr/share/autoconf', str(root / 'usr/share/autoconf'))
    files['env.sh'] = f'''# Source with Bash. Generated by tools/prepare_legacy_build_env.py.
source {shlex.quote(str(deps / 'env.sh'))}
export LEGACY_BUILD_ROOT={shlex.quote(str(output))}
export PATH=$LEGACY_BUILD_ROOT/bin:$PATH
export autom4te_perllibdir=$GIMP_DEPS_ROOT/usr/share/autoconf
export AC_MACRODIR=$GIMP_DEPS_ROOT/usr/share/autoconf
export AUTOM4TE_CFG=$LEGACY_BUILD_ROOT/autom4te.cfg
export AUTOM4TE=$GIMP_DEPS_ROOT/usr/bin/autom4te
export AUTOCONF=$GIMP_DEPS_ROOT/usr/bin/autoconf
export AUTOHEADER=$GIMP_DEPS_ROOT/usr/bin/autoheader
export trailer_m4=$GIMP_DEPS_ROOT/usr/share/autoconf/autoconf/trailer.m4
export M4=$GIMP_DEPS_ROOT/usr/bin/m4
export AUTOMAKE=automake ACLOCAL=aclocal
export AUTOMAKE_LIBDIR=$GIMP_DEPS_ROOT/usr/share/automake-1.17
export ACLOCAL_FLAGS="-I $GIMP_DEPS_ROOT/usr/share/aclocal"
export gettext_datadir=$GIMP_DEPS_ROOT/usr/share/gettext
export PERL5LIB=$GIMP_DEPS_ROOT/usr/share/automake-1.17:$GIMP_DEPS_ROOT/usr/share/perl5:$GIMP_DEPS_ROOT/usr/lib/x86_64-linux-gnu/perl5/5.40${{PERL5LIB:+:$PERL5LIB}}
unset _lt_pkgdatadir
export PKG_CONFIG_PATH=$LEGACY_BUILD_ROOT/prefix/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$LEGACY_BUILD_ROOT/prefix/lib:$LD_LIBRARY_PATH
export BABL_PATH=$LEGACY_BUILD_ROOT/prefix/lib/babl-0.1
export CPPFLAGS="-I$GIMP_DEPS_ROOT/usr/include -I$GIMP_DEPS_ROOT/usr/include/x86_64-linux-gnu"
export LDFLAGS="-L$LEGACY_BUILD_ROOT/prefix/lib -L$GIMP_DEPS_ROOT/usr/lib/x86_64-linux-gnu -Wl,-rpath,$LEGACY_BUILD_ROOT/prefix/lib -Wl,-rpath,$GIMP_DEPS_ROOT/usr/lib/x86_64-linux-gnu"
'''
    for name,text in files.items():
        path = output / name
        path.write_text(text)
        if name.startswith('bin/'):
            path.chmod(0o755)
    manifest = {'schema_version': 1, 'scope': 'Linux x86_64 Debian13 local-prefix build-tool relocation',
                'dependency_directory': str(deps), 'output_directory': str(output),
                'input_sha256': {str(path):sha(path) for path in inputs.values()},
                'generated_sha256': {name:sha(output/name) for name in files},
                'limitations': ['Not a completed legacy application build or runtime validation',
                                'Requires exact signed Debian package lock and source pins recorded separately']}
    (output / 'environment.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(f'source {shlex.quote(str(output / "env.sh"))}')


if __name__ == '__main__':
    main()
